version: '3.9'

networks:
  support-net:
    driver: bridge

services:

  api:
    container_name: api
    restart: always
    build:
      context: ./api
    ports:
    - 8080:8080
    cpu_count: 1
    networks:
    - support-net
    depends_on:
    - database
    # - redis
    deploy:
      resources:
        limits:
          memory: 1024M

  database:
    image: mysql:8
    container_name: database
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: T6y1HrE5265a1vmffVAXA
      MYSQL_DATABASE: scwwts
    ports:
    - 6666:3306
    volumes:
    - ./data/mysql:/var/lib/mysql
    - ./mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    networks:
    - support-net
    deploy:
      resources:
        limits:
          memory: 1024M


# redis:
#   image: redis:latest
#   container_name: redis
#   restart: always
#   ports:
#   - "6379:6379"
#   cpu_count: 1
#   deploy:
#     resources:
#       limits:
#         memory: 1024M
